import type { Metadata } from 'next'
import Link from 'next/link'
import { BahaLogo } from '@/components/ui'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Baha Buddy terms of service. Read the terms governing your use of the Baha Buddy platform.',
  openGraph: {
    title: 'Terms of Service | Baha Buddy',
    description:
      'Terms governing your use of the Baha Buddy platform.',
  },
}

export default function TermsPage() {
  const effectiveDate = 'May 18, 2026'

  return (
    <div className="min-h-screen bg-white">
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <BahaLogo href="/" size="md" />
          <nav className="flex items-center gap-4">
            <Link
              href="/"
              className="text-sm text-gray-600 hover:text-gray-900 transition-colors hidden sm:block"
            >
              Home
            </Link>
            <Link
              href="/login"
              className="text-sm font-medium text-brand-600 hover:text-brand-700 transition-colors"
            >
              Sign in
            </Link>
          </nav>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-14">
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-gray-500 mb-10">
          Effective date: {effectiveDate}
        </p>

        <div className="prose prose-gray max-w-none space-y-8 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-gray-900 [&_h2]:mb-3 [&_p]:text-gray-600 [&_p]:leading-relaxed [&_ul]:text-gray-600 [&_ul]:leading-relaxed">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Baha Buddy (the &quot;Service&quot;),
              operated by Novio Group (&quot;we,&quot; &quot;us,&quot; or
              &quot;our&quot;), you agree to be bound by these Terms of Service
              (&quot;Terms&quot;). If you do not agree to these Terms, do not use
              the Service.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              Baha Buddy is an AI-powered travel companion for the Bahamas. The
              Service includes a mobile application (iOS and Android) and a web
              platform that provide destination information, AI chat-based trip
              planning, flight and hotel search, itinerary management, and
              related travel tools. The Service is intended for personal travel
              planning only.
            </p>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            <p>
              To access certain features, you must create an account using a
              valid email address. You are responsible for maintaining the
              confidentiality of your account credentials and for all activity
              that occurs under your account. You agree to notify us immediately
              of any unauthorized use.
            </p>
          </section>

          <section>
            <h2>4. AI Chat and Recommendations</h2>
            <p>
              Baha Buddy uses artificial intelligence to provide travel
              recommendations, itinerary suggestions, and general information
              about the Bahamas. These responses are generated by AI and are
              provided for informational purposes only. They do not constitute
              professional travel advice, financial advice, or any other form of
              professional guidance.
            </p>
            <p>
              While we strive for accuracy, AI-generated content may contain
              errors or outdated information. You should independently verify
              important details such as pricing, availability, safety
              conditions, and travel requirements before making decisions.
            </p>
          </section>

          <section>
            <h2>5. Payments and Third-Party Bookings</h2>
            <p>
              Payment processing for any premium features or in-app purchases is
              handled by Stripe. By making a payment, you agree to
              Stripe&apos;s terms of service.
            </p>
            <p>
              When you book flights, hotels, or other services through Baha
              Buddy, you are transacting with third-party providers. We
              facilitate the search and display of these options but are not a
              party to the booking contract between you and the provider. We do
              not guarantee the accuracy of third-party pricing, availability, or
              service quality. Cancellation and refund policies are determined by
              the respective provider.
            </p>
          </section>

          <section>
            <h2>6. Prohibited Conduct</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Use the Service for any unlawful purpose or in violation of any
                applicable laws.
              </li>
              <li>
                Attempt to gain unauthorized access to any part of the Service or
                its related systems.
              </li>
              <li>
                Use automated tools (bots, scrapers) to access or collect data
                from the Service without our written consent.
              </li>
              <li>
                Interfere with or disrupt the integrity or performance of the
                Service.
              </li>
              <li>
                Impersonate another person or misrepresent your affiliation with
                any entity.
              </li>
              <li>
                Use the AI chat feature to generate content that is harmful,
                abusive, or violates the rights of others.
              </li>
            </ul>
          </section>

          <section>
            <h2>7. Intellectual Property</h2>
            <p>
              All content, features, and functionality of the Service — including
              text, graphics, logos, and software — are owned by Novio Group and
              are protected by applicable intellectual property laws. You may not
              reproduce, distribute, or create derivative works from any part of
              the Service without our prior written consent.
            </p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Novio Group shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages arising out of or related to your use of the
              Service. Our total liability for any claim arising from the Service
              shall not exceed the amount you paid to us, if any, during the
              twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2>9. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time,
              with or without cause, and with or without notice. You may
              terminate your account at any time by contacting us at{' '}
              <a
                href="mailto:support@bahabuddy.com"
                className="text-brand-600 hover:text-brand-700 underline underline-offset-2"
              >
                support@bahabuddy.com
              </a>{' '}
              or by deleting your account through the app. Upon termination, your
              right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2>10. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will
              notify you of material changes by posting the updated Terms on this
              page and updating the effective date. Your continued use of the
              Service after changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2>11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of the State of Florida, United States of America, without
              regard to its conflict-of-law provisions. Any disputes arising from
              these Terms or the Service shall be resolved in the courts located
              in the State of Florida.
            </p>
          </section>

          <section>
            <h2>12. Contact Us</h2>
            <p>
              If you have questions about these Terms, contact us at:
            </p>
            <p>
              <strong>Novio Group</strong>
              <br />
              Email:{' '}
              <a
                href="mailto:support@bahabuddy.com"
                className="text-brand-600 hover:text-brand-700 underline underline-offset-2"
              >
                support@bahabuddy.com
              </a>
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
